name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

# Cancel a currently running workflow from the same PR/branch/tag
# when a new workflow is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@onekeyhq'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependency
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          set +e  # don't stop on errors
          npm i -g expo-cli@6.0.8 && yarn --mode=skip-build && yarn patch-package
          yarn lint
          echo "LINT_EXIT_CODE=$?" >> $GITHUB_ENV  # store the exit code for use in subsequent steps
        shell: bash
      - name: Extract Pull Request Number
        id: pr_number
        run: echo "PR_NUMBER=$(echo $GITHUB_REF | awk -F '/' '{print $3}')" >> $GITHUB_ENV
      - name: Form Pull Request URL
        id: pr_url
        run: echo "PR_URL=https://github.com/$GITHUB_REPOSITORY/pull/$PR_NUMBER" >> $GITHUB_ENV
      - name: Get Date
        id: date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ====>>> ${{ steps.date.outputs.date }}
            Lint finish
            Repository: ${{ github.repository }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Pull Request: ${{ env.PR_URL }}
            Lint Exit Code: ${{ env.LINT_EXIT_CODE }}  # report the exit code of the lint step

