name: Notice Pull Request

on:
  workflow_run:
    workflows: ["Lint", "Codacy Security Scan"]
    types:
      - completed

jobs:
  final_action_job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Get Pull Request Info
        id: pr_info
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pull_requests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.repo.owner + ":" + context.sha
            });
            if (pull_requests.length > 0 && pull_requests[0].hasOwnProperty('html_url')) {
              return pull_requests[0].html_url;
            }
            return '';

      - name: Set PR html_url
        run: echo "PR_URL=${{ steps.pr_info.outputs.result }}" >> $GITHUB_ENV

      - name: Get Date
        id: date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ====>>> ${{ steps.date.outputs.date }}
            Pull Request finished!
            Repository: ${{ github.repository }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Pull Request: ${{ env.PR_URL }}
